export const Auth = {
  LOGIN_USER_BEGIN: 'auth/LOGIN_USER_BEGIN',
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',

  REGISTER_USER_BEGIN: 'auth/REGISTER_USER_BEGIN',
  REGISTER_USER_SUCCESS: 'auth/REGISTER_USER_SUCCESS',
  REGISTER_USER_FAIL: 'auth/REGISTER_USER_FAIL',

  LOG_OUT: 'auth/LOG_OUT',
};

export const News = {
  GET_TOP_HEADLINES_BEGIN: 'news/GET_TOP_HEADLINES_BEGIN',
  GET_TOP_HEADLINES_SUCCESS: 'news/GET_TOP_HEADLINES_SUCCESS',
  GET_TOP_HEADLINES_FAIL: 'news/GET_TOP_HEADLINES_FAIL',

  GET_NEWS_BY_TOPIC_BEGIN: 'news/GET_NEWS_BY_TOPIC_BEGIN',
  GET_NEWS_BY_TOPIC_SUCCESS: 'news/GET_NEWS_BY_TOPIC_SUCCESS',
  GET_NEWS_BY_TOPIC_FAIL: 'news/GET_NEWS_BY_TOPIC_FAIL',

  GET_MORE_NEWS_FROM_DOMAINS_BEGIN: 'news/GET_MORE_NEWS_FROM_DOMAINS_BEGIN',
  GET_MORE_NEWS_FROM_DOMAINS_SUCCESS: 'news/GET_MORE_NEWS_FROM_DOMAINS_SUCCESS',
  GET_MORE_NEWS_FROM_DOMAINS_FAIL: 'news/GET_MORE_NEWS_FROM_DOMAINS_FAIL',

  GET_HOME_NEWS_DETAIL: 'news/GET_HOME_NEWS_DETAIL',
  GET_EXPLORE_NEWS_DETAIL: 'news/GET_EXPLORE_NEWS_DETAIL',
};
