export const Auth = {
  LOGIN_USER_BEGIN: 'auth/LOGIN_USER_BEGIN',
  LOGIN_USER_SUCCESS: 'auth/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'auth/LOGIN_USER_FAIL',

  REGISTER_USER_BEGIN: 'auth/REGISTER_USER_BEGIN',
  REGISTER_USER_SUCCESS: 'auth/REGISTER_USER_SUCCESS',
  REGISTER_USER_FAIL: 'auth/REGISTER_USER_FAIL',

  LOG_OUT: 'auth/LOG_OUT',
};
